// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCalrulPiGV0F6Xh6-VSRv0n5FpErP4yj0',
    appId: '1:783405718430:web:1f5ef51bfa7028b929d48f',
    messagingSenderId: '783405718430',
    projectId: 'quicknotes-ee1b3',
    authDomain: 'quicknotes-ee1b3.firebaseapp.com',
    storageBucket: 'quicknotes-ee1b3.firebasestorage.app',
    measurementId: 'G-FNVFGDKFYT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAY35Bzvwn1j96I2YqRHDAhJcn5A5Lrq24',
    appId: '1:783405718430:android:63a83e1d2d5b097229d48f',
    messagingSenderId: '783405718430',
    projectId: 'quicknotes-ee1b3',
    storageBucket: 'quicknotes-ee1b3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtv7tncyp0o9lS6GFf8wYL_X9BJm6FjUs',
    appId: '1:783405718430:ios:e5ff580391b1034229d48f',
    messagingSenderId: '783405718430',
    projectId: 'quicknotes-ee1b3',
    storageBucket: 'quicknotes-ee1b3.firebasestorage.app',
    iosBundleId: 'com.example.quicknotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtv7tncyp0o9lS6GFf8wYL_X9BJm6FjUs',
    appId: '1:783405718430:ios:e5ff580391b1034229d48f',
    messagingSenderId: '783405718430',
    projectId: 'quicknotes-ee1b3',
    storageBucket: 'quicknotes-ee1b3.firebasestorage.app',
    iosBundleId: 'com.example.quicknotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCalrulPiGV0F6Xh6-VSRv0n5FpErP4yj0',
    appId: '1:783405718430:web:c5f9ed323adf1b8729d48f',
    messagingSenderId: '783405718430',
    projectId: 'quicknotes-ee1b3',
    authDomain: 'quicknotes-ee1b3.firebaseapp.com',
    storageBucket: 'quicknotes-ee1b3.firebasestorage.app',
    measurementId: 'G-3MYCL4EC3J',
  );
}
